# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarbonFootprint' do
  pod 'TwitterKit', '2.7.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for CarbonFootprint
  pod 'Google/SignIn'

  target 'CarbonFootprintTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
